


install: generate-ssh-key


generate-client-tester: python -m venv ./client-tester
generate-django-backend: python -m venv ./django-backend
generate-flask-backend: python -m venv ./flask-backend
generate-enviorments: generate-client-tester generate-django-backend generate-flask-backend

generate-ssh-key:  openssl req -new -newkey rsa:4096 -x509 -sha256 -days 365 -nodes -out MyCertificate.crt -keyout MyKey.key